trigger:
  branches:
    include:
      - refs/tags/release-v*

pr: none

pool:
  vmImage: 'macOS-13'

variables:
  - group: nuget.org

steps:

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    useGlobalJson: true

- bash: |
    echo "##vso[task.setvariable variable=bindingsVersion]$(cat Tonestro.Maui.Kotlin.Parcelize.Runtime/Tonestro.Maui.Kotlin.Parcelize.Runtime.csproj | grep '<Version>' | awk -F '[<>]' '{print $3}')"
  displayName: Set Build Number

- bash: |
    sudo dotnet workload restore
  displayName: Restore workloads

- bash: |
    echo "##vso[build.updatebuildnumber]production-maui-kotlin-parcelize-runtime-bindings-$(Build.SourceBranchName)-$(Build.BuildId)"

- bash: |
    if [[ "$(Build.SourceBranchName)" != *"$(bindingsVersion)" ]]; then
      echo "mismatch between tag $(Build.SourceBranchName) and nuget version $(bindingsVersion)"
      exit 1
    fi

- bash: |
    sudo dotnet workload restore
  displayName: Restore workloads

- bash: |
    cd Tonestro.Maui.Kotlin.Android.Extensions.Runtime
    dotnet restore
    dotnet build --configuration Release
    dotnet pack --configuration Release
  displayName: "Tonestro.Maui.Kotlin.Android.Extensions.Runtime: Build Release Nuget"

- bash: |
    cd Tonestro.Maui.Kotlin.Parcelize.Runtime
    dotnet restore
    dotnet build --configuration Release
    dotnet pack --configuration Release
  displayName: "Tonestro.Maui.Kotlin.Parcelize.Runtime: Build Release Nuget"

- bash: |
    ./copy-nugets.sh
  displayName: "Copy nugets to nugetoutput folder"

- bash: |
    dotnet nuget push nugetoutput/Tonestro.Maui.Kotlin.Android.Extensions.Runtime.$(bindingsVersion).nupkg -k "$(nugetOrgApiKey)" -s https://api.nuget.org/v3/index.json
    dotnet nuget push nugetoutput/Tonestro.Maui.Kotlin.Parcelize.Runtime.$(bindingsVersion).nupkg -k "$(nugetOrgApiKey)" -s https://api.nuget.org/v3/index.json
  displayName: "Publish nuget packages to nuget.org"

- task: GitHubRelease@1
  inputs:
    gitHubConnection: 'github.com_thisisthekap'
    repositoryName: 'thisisthekap/Tonestro.Maui.Kotlin.Parcelize.Runtime'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: 'userSpecifiedTag'
    tag: '$(Build.SourceBranchName)'
    title: 'Tonestro.Maui.Kotlin.Parcelize.Runtime $(bindingsVersion)'
    assets: 'nugetoutput/Tonestro.Maui.Kotlin.Parcelize.Runtime.*.nupkg'
    changeLogCompareToRelease: 'lastFullRelease'
    changeLogType: 'issueBased'
